<Project>
  <Target
    Name="HuskyInstall"
    BeforeTargets="Restore;CollectPackageReferences"
    Condition="'$(HUSKY)' != 0 AND '$(MSBuildProjectName)' == 'SpecFirst.Service.Api' AND Exists('$(MSBuildThisFileDirectory).git')"
  >
    <Exec
      Command="dotnet tool restore"
      StandardOutputImportance="Low"
      WorkingDirectory="$(MSBuildThisFileDirectory)"
    />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      WorkingDirectory="$(MSBuildThisFileDirectory)"
    />
  </Target>
</Project>
