CREATE TABLE public."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL
);
CREATE TABLE public.order_lines (
    id bigint NOT NULL,
    order_id uuid NOT NULL,
    sku character varying(64) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(18,2) NOT NULL
);
ALTER TABLE public.order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.orders (
    id uuid NOT NULL,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL
);
ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id);
ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT pk_order_lines PRIMARY KEY (id);
ALTER TABLE ONLY public.orders
    ADD CONSTRAINT pk_orders PRIMARY KEY (id);
CREATE INDEX ix_order_lines_order_id ON public.order_lines USING btree (order_id);
ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT fk_order_lines_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
